### ISSUE TITLE
Read on Verified Contract does not work

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/blockscout#79]
### Description

Reading from a verified contract does not work on production block explorers.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Unknown

### Type of the chain

elated-tan-skat - production - medium skale chain

### Link to the page

https://elated-tan-skat.explorer.mainnet.skalenodes.com/address/0x5F795bb52dAC3085f578f4877D450e2929D2F13d?tab=read_contract

### Steps to reproduce

1. Go to https://elated-tan-skat.explorer.mainnet.skalenodes.com/address/0x5F795bb52dAC3085f578f4877D450e2929D2F13d?tab=read_contract
2. Open Logs

### Backend version

Unknown

### Frontend version

Unknown

### Elixir & Erlang/OTP versions

Unknown

### Operating system

MacOS - Chrome

### Additional information

<img width="1719" alt="image" src="https://github.com/user-attachments/assets/4ff81aeb-3d3f-4faf-837a-bbd90006773a">

**Comment by lianliss** [comment]
We can often turn to the explorer to read the contract data. Reading any contract in the SKALE Europa (elated-tan-skat) network does not work at all now - the error "Too Long Response" is returned.

At the same time, in the SKALE Europa Testnet (juicy-low-small-testnet) network, the explorer works acceptably.

We also ask you to check the entry in the contract through the explorer (with Metamask connected, for example). The form freezes after sending the request. The request may complete successfully, but the form will not change, and in order to execute a new request, you have to reload the page with a reset of all form fields.

**Comment by PolinaKiporenko** [comment]
should be fixed on Hubs

**Comment by PolinaKiporenko** [comment]
fixed
